version: '3'
services:
    app:
        build: .
        depends_on:
            - db_host
        ports:
            - "5000:5000"

    db_host:
        image: mongo:latest
        container_name: "mongodb"
        ports:
            - "27017:27017"
